=== Rubru94/jugon.es/docs/XML/plataformas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="jugones">
		<complexType>
			<sequence>
				<element name="plataformas">
					<complexType>
						<sequence>
							<element name="plataforma" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="nombre">
											<simpleType> 
												<restriction base="string">
													<whiteSpace value="collapse"/>
													<maxLength value="50" /> 
												</restriction>
											</simpleType>
										</element>
										<element name="compania">
											<simpleType> 
												<restriction base="string">
													<whiteSpace value="collapse"/>
													<maxLength value="50" /> 
												</restriction>
											</simpleType>
										</element>
										<element name="generacion">
											<simpleType> 
												<restriction base="string">
													<whiteSpace value="collapse"/>
													<maxLength value="10" /> 
												</restriction>
											</simpleType>
										</element>
										<element name="lanzamiento">
											<simpleType> 
												<restriction base="integer">
													<minInclusive value="1972"/>
													<maxInclusive value="1999"/>
												</restriction>
											</simpleType>
										</element>
										<element name="cpu" type="string"/>
										<element name="gpu" type="string" minOccurs="0"/>
										<element name="juegoMasVendido" type="string" minOccurs="0"/>
										<element name="portada" type="string" minOccurs="0"/>
										<element name="unidadesVendidas" type="integer"/>
										<element name="descripcion">
											<complexType mixed="true"> 
												<choice minOccurs="0" maxOccurs="unbounded"> <!--No importa orden ni numero-->
													<element name="consola" type="string"/>
													<element name="juego" type="string"/>
												</choice>
											</complexType>
										</element>
										
									</sequence>
									<attribute name="codigo" use="required">
										<simpleType> 
											<restriction base="string">
												<whiteSpace value="collapse"/>
												<pattern value="[A-Z0-9]{3,4}"/>
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="tipo" use="required">
										<simpleType> 
											<restriction base="string">
												<enumeration value="sobremesa"/> 
												<enumeration value="portatil"/> 
												<enumeration value="computadora"/>
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="soporteJuego" use="optional">
										<simpleType> 
											<restriction base="string">
												<whiteSpace value="collapse"/>
											</restriction>
										</simpleType>
									</attribute>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
  </element>
</schema>

=== Rubru94/jugon.es/docs/XML/plataformas3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="plataformas3.xsl"?>

<jugones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plataformas.xsd">

	<plataformas>
		<plataforma codigo="MAOD" tipo="sobremesa" soporteJuego="cartucho">
			<nombre>Magnavox Odyssey</nombre>
			<compania>Magnavox</compania>
			<generacion>Primera</generacion>
			<lanzamiento>1972</lanzamiento>
			<cpu>Ninguno. Constaba de transistores, resistencias y condensadores.</cpu>
			<unidadesVendidas>350000</unidadesVendidas>
			<descripcion>
				Comercializada por la filial de Philips en Estados Unidos, la 
				<consola>Magnavox Odyssey</consola> es la primera videoconsola de la historia, 
				y fue desarrollada por Ralph Baer (apodado «el padre de 
				los videojuegos»). Únicamente dibujaba un punto móvil y 
				barras verticales en la pantalla, por lo que era necesario 
				jugar con plantillas en el televisor. El lanzamiento de la 
				<consola>Odyssey</consola> generó en todo el mundo un caso severo de la 
				“locura de <juego>Pong</juego>”, y compañías por todo el mundo comenzaron 
				a desarrollar sus propias máquinas.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="AT26" tipo="sobremesa" soporteJuego="cartucho casete">
			<nombre>Atari 2600</nombre>
			<compania>Atari</compania>
			<generacion>Segunda</generacion>
			<lanzamiento>1977</lanzamiento>
			<cpu>8-bit MOS Technology 6507</cpu>
			<juegoMasVendido>Pac-Man</juegoMasVendido>
			<portada>1.- PacMan.jpg</portada>
			<unidadesVendidas>30000000</unidadesVendidas>
			<descripcion>
				Todo un éxito en ventas que impulsó a Atari a la fama e hizo
				popular los cartuchos intercambiables. Con sólo 128 bytes de 
				memoria RAM, sacó al mercado juegos como <juego>Pac-man</juego>, 
				<juego>Space Invaders</juego>,<juego>Asteroids</juego>,
				<juego>Donkey Kong</juego>, o <juego>Mario Bros</juego>. 
				Se vendía acompañada de 2 joysticks, 2 controles tipo paddle 
				y el juego <juego>Combat</juego> desde 1977 hasta 1983. 
				La programación de juegos no cesó hasta el año 1989.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="GAW" tipo="portatil" soporteJuego="juego integrado">
			<nombre>Game &amp; Watch</nombre>
			<compania>Nintendo</compania>
			<generacion>Segunda</generacion>
			<lanzamiento>1981</lanzamiento>
			<cpu>Calculadora</cpu>
			<juegoMasVendido>Donkey Kong</juegoMasVendido>
			<portada>2.- DonkeyKong.gif</portada>
			<unidadesVendidas>40000000</unidadesVendidas>
			<descripcion>
				La serie <consola>Game &amp; Watch</consola> era una línea de 
				aproximadamente 59 juegos electrónicos portátiles que consistían
				de un solo juego que se podía jugar en una o dos pantallas LCD, 
				además de ser un reloj y alarma. Algunos de los títulos del formato 
				<consola>Game &amp; Watch</consola> fueron <juego>Pinball</juego>, 
				<juego>Donkey Kong</juego>, <juego>The Legend of Zelda</juego>, 
				<juego>Mario Bros</juego>, y <juego>Ballon Fight</juego>.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="ZXSP" tipo="computadora" soporteJuego="cartucho casete">
			<nombre>ZX Spectrum</nombre>
			<compania>Sinclair</compania>
			<generacion>Segunda</generacion>
			<lanzamiento>1982</lanzamiento>
			<cpu>8 bits Zilog Z80A @ 4 MHz</cpu>
			
			<unidadesVendidas>6000000</unidadesVendidas>
			<descripcion>
				Se trata de uno de los ordenadores de 8 bits más populares de los 
				años 80 (sobretodo en Europa). Su diseño se optimizó mucho, 
				exprimiendo sus escasos recursos (respecto a la competencia). 
				Era una máquina asequible que acercó la microinformática a 
				muchos hogares. Tuvo juegos tan famosos como <juego>R-Type</juego> 
				y <juego>Renegade</juego>.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="CO64" tipo="computadora" soporteJuego="cartucho casete">
			<nombre>Commodore 64</nombre>
			<compania>Commodore International</compania>
			<generacion>Segunda</generacion>
			<lanzamiento>1982</lanzamiento>
			<cpu>MOS 6510</cpu>
			
			<unidadesVendidas>12500000</unidadesVendidas>
			<descripcion>
				Uno de los mejores ordenadores de 8 bits, con un catálogo de juegos 
				muy extenso. Tenía 64 kilobytes de RAM y el mejor chip de sonido 
				de la época, por lo que muchos músicos hicieron uso de él 
				para componer. Usaba un scroll de pantalla muy suave que daba a 
				los juegos un toque especial de realismo. Salieron juegos como 
				<juego>Test Drive</juego>, <juego>Last Ninja</juego>, 
				<juego>Shadow of the Beast</juego>, <juego>Maniac Mansion</juego>, 
				o la serie <juego>Ultima</juego>. 
			</descripcion>
		</plataforma>
		
		<plataforma codigo="MSX" tipo="computadora" soporteJuego="cartucho casete">
			<nombre>MSX</nombre>
			<compania>Kazuhiko Nishi. Más tarde licenciado por Sony</compania>
			<generacion>Segunda</generacion>
			<lanzamiento>1983</lanzamiento>
			<cpu>Zilog Z80</cpu>
			
			<unidadesVendidas>4000000</unidadesVendidas>	
			<descripcion>
				Ordenador doméstico que inició sagas tan populares que hoy en 
				día conocemos cómo <juego>Bomberman</juego>, <juego>Metal Gear</juego>,
				<juego>Castlevania</juego>, <juego>Dragon Quest</juego>, 
				<juego>Final Fantasy</juego>, etc. Su Microprocesador Z80 fue muy 
				utilizado en los ordenadores domésticos de la época tales como 
				<consola>Spectrum</consola>, <consola>Amstrad CPC</consola> o 
				<consola>Commodore 128</consola> y actuó como procesador secundario 
				en las <consola>Game Boy</consola>.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="ACPC" tipo="computadora" soporteJuego="cartucho casete">
			<nombre>Amstrad CPC</nombre>
			<compania>Amstrad</compania>
			<generacion>Segunda</generacion>
			<lanzamiento>1984</lanzamiento>
			<cpu>Zilog Z80A @ 4 MHz</cpu>
			
			<unidadesVendidas>3000000</unidadesVendidas>	
			<descripcion>
				Serie de ordenadores personales de 8 bits diseñados para ser un 
				competidor directo al <consola>Commodore 64</consola> y al 
				<consola>Sinclair ZX Spectrum</consola>, y así fue, tuvo 
				mucho éxito. Lo que más distingue a la máquina de Amstrad es 
				la consola (teclado) negro mate con las esquinas agudas y una 
				forma rectangular. También era posible utilizar el monitor como
				pantalla de televisión con un convertidor de TV opcional.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="NES" tipo="sobremesa" soporteJuego="cartucho">
			<nombre>Nintendo Entertaiment System</nombre>
			<compania>Nintendo</compania>
			<generacion>Tercera</generacion>
			<lanzamiento>1985</lanzamiento>
			<cpu>Unidad Ricoh 2A03 de 8 bits (procesador MOS 6502)</cpu>
			<juegoMasVendido>Super Mario Bros</juegoMasVendido>
			<portada>3.- SuperMarioBros.jpg</portada>
			<unidadesVendidas>61910000</unidadesVendidas>	
			<descripcion>
				La primera consola de Nintendo y la que supuso un auténtico boom 
				en el mundo de los videojuegos, vendiendo aproximadamente 60 millones
				de unidades. Definió cómo tenían que ser los juegos y cómo jugarlos, 
				gracias a su cruceta direccional inventada por Gunpei Yokoi, 
				que sustituiría el ya antiguo joystick de los hogares. 
				Gracias a su éxito en ventas: <juego>Super Mario Bros</juego>, 
				Nintendo puso de moda el género de los juegos de plataformas.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="SMS" tipo="sobremesa" soporteJuego="cartucho">
			<nombre>SEGA Master System</nombre>
			<compania>SEGA</compania>
			<generacion>Tercera</generacion>
			<lanzamiento>1986</lanzamiento>
			<cpu>Zilog Z80A a 3,5 MHz</cpu>
			<gpu>Texas Instruments TMS9918</gpu>
			<juegoMasVendido>Alex Kidd in Miracle World</juegoMasVendido>
			<portada>4.- AlexKidd.jpg</portada>
			<unidadesVendidas>13000000</unidadesVendidas>	
			<descripcion>
				Sega rediseñó su <consola>SG-1000 Mark III</consola> y le cambió 
				el nombre a <consola>Master System</consola>. Más adelante la 
				volvieron a rediseñar, haciéndola más compacta, y se dió a conocer
				como <consola>Master System II</consola>, quizás el rediseño más 
				famoso en el mundo de los videojuegos. Venía con un juego 
				preinstalado, <juego>Alex Kidd in Miracle World</juego>, que fue
				muy popular debido a que muchas tiendas lo ponían en un televisor 
				en sus escaparates. Fue la principal competidora de la <consola>NES</consola>
				de Nintendo, la cual tenía un catálogo mucho más amplio, pero era 
				más pobre gráficamente.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="SMD" tipo="sobremesa" soporteJuego="cartucho">
			<nombre>SEGA Mega Drive</nombre>
			<compania>SEGA</compania>
			<generacion>Cuarta</generacion>
			<lanzamiento>1988</lanzamiento>
			<cpu>Motorola 68000 @ 7.61 MHz/Zilog Z80 @ 3.58 MHz</cpu>
			<juegoMasVendido>Sonic the Hedgehog</juegoMasVendido>
			<portada>5.- SonicMD.png</portada>
			<unidadesVendidas>30750000</unidadesVendidas>	
			<descripcion>
				Incorporó una CPU de 32 bits montada sobre un bus de datos de 16, 
				por lo que su arquitectura fue finalmente de 16 bits. No tuvo 
				demasiado éxito en Japón, pero en América y Europa fue la líder 
				indiscutible, incluso estuvo por encima de la 
				<consola>Super Nintendo</consola> (su principal competidora) 
				en estos continentes, a parte de tener un catálogo de juegos mucho 
				más extenso y variado. El gran público no le prestó demasiada 
				atención hasta que apareció <juego>Sonic the Hedgehog</juego>. 
				Su principal atractivo eran sus juegos directamente convertidos 
				desde las recreativas.
			</descripcion>
		</plataforma>
		
		<plataforma codigo="NGB" tipo="portatil" soporteJuego="cartucho">
			<nombre>Game Boy</nombre>
			<compania>Nintendo</compania>
			<generacion>Cuarta</generacion>
			<lanzamiento>1989</lanzamiento>
			<cpu>Sharp LR35902 de 8 bits a 4.19 MHz</cpu>
			<juegoMasVendido>Tetris</juegoMasVendido>
			<portada>6.- Tetris.png</portada>
			<unidadesVendidas>87660000</unidadesVendidas>
			<descripcion>
